language: python

sudo: false

branches:
    only:
      - master

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
    - os: linux
      python: pypy3


install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt

script:
  - pytest --cov-report term-missing --cov=edipy tests

after_success:
  - coveralls
